list(APPEND CMAKE_FIND_LIBRARY_SUFFIXES ".so.6")
find_library(TINFO_LIB "libtinfo.so.6")
if (TINFO_LIB-NOTFOUND)
    message(FATAL_ERROR "TInfo not found")
endif()
find_library(NCURSESW_LIB "libncursesw.so.6")
if (NCURSESW_LIB-NOTFOUND)
    message(FATAL_ERROR "NCursesW not found")
endif()
find_library(FORMW_LIB "libformw.so.6")
if (FORMW_LIB-NOTFOUND)
    message(FATAL_ERROR "FowmW not found")
endif()
set(CURSES_LIBRARIES ${TINFO_LIB} ${NCURSESW_LIB} ${FORMW_LIB})
list(REMOVE_ITEM CMAKE_FIND_LIBRARY_SUFFIXES ".so.6")

